using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DegCAD
{
    /// <summary>
    /// Contains Monge items generated by one command
    /// </summary>
    public class TimelineItem
    {
        public IMongeItem[] Items { get; set; }


        public TimelineItem(IMongeItem[] items)
        {
            Items = items;
        }
    }
}
